import os
from reportlab.lib.pagesizes import letter, A4
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
import qrcode
from io import BytesIO

def generate_ticket_pdf(booking_data):
    """
    Generates a PDF ticket for the given booking data.
    booking_data: dict containing museum_name, user_name, date, tickets, booking_id
    Returns: BytesIO object containing the PDF
    """
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4
    
    # --- Design Colors ---
    primary_color = (0.54, 0.27, 0.07) # #8B4513 (SaddleBrown)
    text_color = (0.2, 0.2, 0.2)
    
    # --- Header ---
    c.setFillColorRGB(*primary_color)
    c.rect(0, height - 100, width, 100, fill=1, stroke=0)
    
    c.setFillColorRGB(1, 1, 1) # White text
    c.setFont("Helvetica-Bold", 30)
    c.drawCentredString(width / 2, height - 60, "MUSEUM TICKET")
    
    # --- Museum Details ---
    c.setFillColorRGB(*text_color)
    c.setFont("Helvetica-Bold", 22)
    c.drawCentredString(width / 2, height - 150, booking_data.get('museum_name', 'Museum'))
    
    # --- Ticket Info Box ---
    c.setStrokeColorRGB(*primary_color)
    c.setLineWidth(2)
    c.rect(50, height - 400, width - 100, 200, stroke=1, fill=0)
    
    y_pos = height - 250
    x_left = 80
    x_val = 200
    
    c.setFont("Helvetica", 14)
    
    fields = [
        ("Visitor:", booking_data.get('user_name', 'Visitor')),
        ("Date:", booking_data.get('date', 'N/A')),
        ("Tickets:", str(booking_data.get('tickets', 1))),
        ("Booking ID:", str(booking_data.get('booking_id', 'N/A')))
    ]
    
    for label, value in fields:
        c.setFont("Helvetica-Bold", 14)
        c.drawString(x_left, y_pos, label)
        c.setFont("Helvetica", 14)
        c.drawString(x_val, y_pos, value)
        y_pos -= 30
    
    # --- QR Code ---
    # Create QR code with Booking ID
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=10,
        border=4,
    )
    qr.add_data(str(booking_data.get('booking_id')))
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")
    
    # Save QR to a temporary buffer to draw on PDF
    qr_buffer = BytesIO()
    img.save(qr_buffer)
    qr_buffer.seek(0)
    
    c.drawImage(ImageReader(qr_buffer), width - 200, height - 380, width=120, height=120)
    c.drawString(width - 180, height - 395, "Scan to Verify")

    # --- Footer ---
    c.setFont("Helvetica-Oblique", 10)
    c.drawCentredString(width / 2, 50, "Thank you for preserving our heritage. Enjoy your visit!")
    c.drawCentredString(width / 2, 35, "Generated by PixelPast Museum Management System")
    
    c.save()
    buffer.seek(0)
    return buffer
